# Development overrides
version: '3.8'

services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pipe_db_dev
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dev_password

  redis:
    ports:
      - "6379:6379"

  neo4j:
    environment:
      NEO4J_AUTH: neo4j/dev_password
      NEO4J_dbms_connector_bolt_advertised__address: localhost:7687
      NEO4J_dbms_connector_http_advertised__address: localhost:7474