version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pipe-postgres
    environment:
      POSTGRES_DB: pipe_db
      POSTGRES_USER: pipe_user
      POSTGRES_PASSWORD: pipe_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pipe_user -d pipe_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: pipe-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for PostgreSQL management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pipe-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pipe.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    profiles:
      - dev-tools

  # Optional: RedisInsight for Redis management
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: pipe-redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis
    profiles:
      - dev-tools

volumes:
  postgres_data:
  redis_data: