[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build && npx prisma generate"

[deploy]
startCommand = "npm run db:migrate:deploy && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "pipe-api"
icon = "🚀"

[services.domains]
"$production" = "pipe-production.up.railway.app"